#!/usr/bin/env python3
"""Witness artifacts for the second locality pass, RFC 5545 SS3 corpus
(see README.md — registration pushed at main 8821bce BEFORE any entry
below was written).

Graded by `check_witnesses2.py`. Each entry names its READING, its QUOTE
(the corpus sentence, [n] = item number in
census/ical/rfc5545_s3_musts.txt, corpus-verbatim), and the artifact.

MODELING CONVENTIONS (disclosed; they bound what the mechanical checks
certify — the first study's convention 1 carries over):

1. ABSTRACT CONTENT-LINE MODEL. A prop datum is a dict {"name",
   "params": {...}, "value", "component": [enclosing component-type
   chain]}; an object datum is a nested dict {"type", "props": [...],
   "components": [...]} rooted at VCALENDAR. Values are parsed abstract
   forms (a RECUR value is a dict of rule parts; a DATE or DATE-TIME
   value carries a "vtype" and, where a witness needs arithmetic, an
   integer day index — recurrence expansion is modeled over integer day
   arithmetic, not calendar math). The mechanical checks certify
   INFORMATION FLOW, not parser implementations.

2. DENOTATION-CARRYING VALUES (item 84). An abstract UTC-OFFSET value
   carries both its encoded sign character and its signed denotation
   ({"encoded_sign", "offset_minutes"}), so encoding-vs-denotation
   consistency duties are checkable in-datum. This is the format-genre
   instance of convention 1: the abstract value is what the presentation
   grammar defines, which includes the sign character.

3. CHANNEL ATTACHMENT. "party-conduct" attaches to the application the
   sentence obliges (parser, generator, or consumer); an application's
   recognized-vocabulary set is its OWN configuration
   ("deployment-policy"); "other-artifacts" covers other iCalendar
   objects and iTIP scheduling transactions; "world-fact" covers
   leap-second history and time-zone law.

4. ANAPHORA DESIGNATIONS (registered): 143 -> VERSION, 192/193/194 ->
   RECURRENCE-ID. Each affected reading restates its designation.
"""

# --- model helpers ---------------------------------------------------------


def P(name, value, params=None, component=("VCALENDAR",)):
    return {"name": name, "value": value, "params": dict(params or {}),
            "component": list(component)}


def C(ctype, props, subs=()):
    return {"type": ctype, "props": list(props), "components": list(subs)}


def OBJ(props, subs=()):
    return C("VCALENDAR", props, subs)


def walk(comp, chain=None):
    """Yield (component-chain, prop) over a nested object."""
    chain = (chain or []) + [comp["type"]]
    for p in comp["props"]:
        yield chain, p
    for sub in comp["components"]:
        yield from walk(sub, chain)


def find_props(obj, name, ctype=None):
    return [(ch, p) for ch, p in walk(obj)
            if p["name"] == name and (ctype is None or ch[-1] == ctype)]


def ctx(desc, channel, verdict, quote):
    return {"desc": desc, "channel": channel, "verdict": verdict,
            "quote": quote}


def PAIR(item, reading, datum, c1, c2, eligible=True):
    return {"item": item, "reading": reading, "rung": "nonlocal",
            "eligible": eligible, "kind": "pair",
            "pair": {"datum_kind": "object", "datum": datum,
                     "contexts": [c1, c2]}}


def VAL(item, reading, rung, fn, accept, reject, quote, eligible=True,
        pair_fine=None):
    w = {"item": item, "reading": reading, "rung": rung,
         "eligible": eligible, "kind": "validator", "fn": fn,
         "accept": accept, "reject": reject, "quote": quote}
    if pair_fine is not None:
        w["pair_fine"] = pair_fine
    return w


def PPAIR(datum, c1, c2):
    return {"datum_kind": "prop", "datum": datum, "contexts": [c1, c2]}


# Corpus-verbatim quotes (mechanically extracted from
# census/ical/rfc5545_s3_musts.txt).
Q = {
    1: 'When parsing a content line, folded lines MUST first be unfolded '
       'according to the unfolding procedure described above. [1]',
    7: 'Multi-valued properties MUST NOT be used to specify multiple '
       'language variants of the same value. [7]',
    13: "Applications MUST ignore x-param and iana-param values they "
        "don't recognize. [13]",
    43: 'To properly communicate a fixed time in a property value, '
        'either UTC time or local time with time zone reference MUST be '
        'specified. [43]',
    62: 'These rule parts MUST be ignored in RECUR value that violate '
        'the above requirement (e.g., generated by applications that '
        'pre-date this revision of iCalendar). [62]',
    63: 'The BYDAY rule part MUST NOT be specified with a numeric value '
        'when the FREQ rule part is not set to MONTHLY or YEARLY. [63]',
    69: 'Such recurrence instances MUST be ignored and MUST NOT be '
        'counted as part of the recurrence set. [69]',
    77: 'The seconds value of 60 MUST only be used to account for '
        'positive "leap" seconds. [77]',
    79: 'To properly communicate a fixed time in a property value, '
        'either UTC time or local time with time zone reference MUST be '
        'specified. [79]',
    84: 'The HYPHEN-MINUS character MUST be specified for negative UTC '
        'offsets (i.e., behind of UTC). [84]',
    91: "Applications MUST ignore x-comp and iana-comp values they "
        "don't recognize. [91]",
    116: '*  If observance is known to have an effective end date, the '
         '"UNTIL" recurrence rule parameter MUST be used to specify the '
         'last valid onset of this observance (i.e., the UNTIL DATE-TIME '
         'will be equal to the last instance generated by the recurrence '
         'pattern). [116]',
    118: '*  The "DTSTART" and the "TZOFFSETFROM" properties MUST be '
         'used when generating the onset DATE-TIME values (instances) '
         'from the "RRULE". [118]',
    143: 'Conformance:  This property MUST be specified once in an '
         'iCalendar object. [143]',
    146: 'Applications MUST treat x-name and iana-token values they '
         "don't recognize the same way as they would the PRIVATE "
         'value. [146]',
    150: 'Receiving applications MUST accept values of this precision '
         'and MAY truncate values of greater precision. [150]',
    185: 'A recipient delegated a request MUST inherit the "RSVP" and '
         '"ROLE" values from the attendee that delegated the request to '
         'them. [185]',
    192: 'This property MUST have the same value type as the "DTSTART" '
         'property contained within the recurring component. [192]',
    193: 'Furthermore, this property MUST be specified as a date with '
         'local time if and only if the "DTSTART" property contained '
         'within the recurring component is specified as a date with '
         'local time. [193]',
    194: 'If the value of the "DTSTART" property is a DATE type value, '
         'then the value MUST be the calendar date for the recurrence '
         'instance. [194]',
    200: 'Description:  The "UID" itself MUST be a globally unique '
         'identifier. [200]',
    201: 'The generator of the identifier MUST guarantee that the '
         'identifier is unique. [201]',
    210: 'Applications MUST ignore alarms with x-name and iana-token '
         "values they don't recognize. [210]",
}

# --- shared model fixtures -------------------------------------------------

# Recurrence expansion over integer day indices (convention 1):
# instances(d0, step, count) or bounded by UNTIL.


def _instances_until(d0, step, until):
    out, d = [], d0
    while d <= until:
        out.append(d)
        d += step
    return out


# A floating (no-TZID, no-UTC) DATE-TIME event — the 43/79 shared datum.
FLOATING_OBJ = OBJ([P("VERSION", "2.0"), P("PRODID", "-//x//y//EN")], [
    C("VEVENT", [
        P("UID", "e1@x"),
        P("DTSTART", {"vtype": "DATE-TIME", "form": "local-floating",
                      "day": 100, "time": "090000"},
          component=("VCALENDAR", "VEVENT")),
        P("SUMMARY", "call", component=("VCALENDAR", "VEVENT")),
    ])])

# DATE-valued DTSTART with an RRULE carrying BYHOUR (violating item 61's
# stated requirement) — item 62's datum.
RECUR_VIOL_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [
        P("UID", "e2@x"),
        P("DTSTART", {"vtype": "DATE", "day": 200},
          component=("VCALENDAR", "VEVENT")),
        P("RRULE", {"FREQ": "DAILY", "COUNT": 3, "BYHOUR": [9]},
          component=("VCALENDAR", "VEVENT")),
    ])])

# An event whose DTSTART carries seconds=60 — item 77's datum.
LEAP_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [
        P("UID", "e3@x"),
        P("DTSTART", {"vtype": "DATE-TIME", "form": "utc", "day": 300,
                      "time": "235960"},
          component=("VCALENDAR", "VEVENT")),
    ])])

# An object with one X- parameter on a property — items 13's datum.
XPARAM_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [
        P("UID", "e4@x"),
        P("SUMMARY", "standup", params={"X-PRIORITY-HINT": "HIGH"},
          component=("VCALENDAR", "VEVENT")),
    ])])

# An object with an unrecognized component type — item 91's datum.
XCOMP_OBJ = OBJ([P("VERSION", "2.0")],
                [C("X-DAILY-DIGEST", [P("UID", "e5@x")])])

# CLASS with an unregistered token — item 146's datum.
XCLASS_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [P("UID", "e6@x"),
                 P("CLASS", "X-EYES-ONLY",
                   component=("VCALENDAR", "VEVENT"))])])

# GEO at the spec's stated six-decimal precision — item 150's datum.
GEO_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [P("UID", "e7@x"),
                 P("GEO", {"lat": "37.386013", "lon": "-122.082932"},
                   component=("VCALENDAR", "VEVENT"))])])

# A VALARM whose ACTION is an x-name — item 210's datum.
XALARM_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [P("UID", "e8@x")],
      [C("VALARM", [P("ACTION", "X-FLASH-LIGHTS",
                      component=("VCALENDAR", "VEVENT", "VALARM"))])])])

# An RRULE generating an invalid instance (modeled: day index flagged
# nonexistent, the abstract stand-in for 30 February) — item 69's datum.
INVALID_INSTANCE_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [
        P("UID", "e9@x"),
        P("DTSTART", {"vtype": "DATE", "day": 400},
          component=("VCALENDAR", "VEVENT")),
        P("RRULE", {"FREQ": "MONTHLY", "COUNT": 3,
                    "note": "third expansion falls on a nonexistent date"},
          component=("VCALENDAR", "VEVENT")),
    ])])

# A VTIMEZONE (used by 118 and 116's nonlocal half).
TZ_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VTIMEZONE", [P("TZID", "America/Metropolis")], [
        C("DAYLIGHT", [
            P("DTSTART", {"vtype": "DATE-TIME", "form": "local", "day": 0},
              component=("VCALENDAR", "VTIMEZONE", "DAYLIGHT")),
            P("TZOFFSETFROM", {"encoded_sign": "-", "offset_minutes": -300},
              component=("VCALENDAR", "VTIMEZONE", "DAYLIGHT")),
            P("TZOFFSETTO", {"encoded_sign": "-", "offset_minutes": -240},
              component=("VCALENDAR", "VTIMEZONE", "DAYLIGHT")),
            P("RRULE", {"FREQ": "YEARLY", "step": 365},
              component=("VCALENDAR", "VTIMEZONE", "DAYLIGHT")),
        ])])])

# An object folded on the wire (its unfolded abstract form) — item 1.
FOLDED_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [P("UID", "e10@x"),
                 P("DESCRIPTION", "a long text that was line-folded in "
                   "transit", component=("VCALENDAR", "VEVENT"))])])

# Two objects sharing the UID value "u-7f3a" exist in the world (context
# narration only; the datum is ONE of them) — items 200/201.
UID_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [P("UID", "u-7f3a", component=("VCALENDAR", "VEVENT"))])])

# CATEGORIES with two values — item 7's datum.
CAT_OBJ = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [P("UID", "e11@x"),
                 P("CATEGORIES", ["MEETING", "REUNION"],
                   component=("VCALENDAR", "VEVENT"))])])


# --- validators (stable DOMAIN + the 192-194 cluster + multis) -------------


def v63(prop):
    """BYDAY numeric modifiers only under FREQ=MONTHLY/YEARLY, within one
    RECUR value."""
    if prop["name"] != "RRULE":
        return False
    r = prop["value"]
    if any(n is not None for n, _d in r.get("BYDAY", [])):
        return r.get("FREQ") in ("MONTHLY", "YEARLY")
    return True


def v84(prop):
    """Encoded sign is HYPHEN-MINUS whenever the offset denotes behind
    UTC (convention 2)."""
    if prop["name"] not in ("TZOFFSETFROM", "TZOFFSETTO"):
        return False
    v = prop["value"]
    if v["offset_minutes"] < 0:
        return v["encoded_sign"] == "-"
    return True


def v143(obj):
    """Exactly one VERSION property at calendar level (designation:
    VERSION — the adjacent item 142 carries PRODID's parallel clause)."""
    return len([p for p in obj["props"] if p["name"] == "VERSION"]) == 1


def _vtype(comp, name):
    for p in comp["props"]:
        if p["name"] == name:
            return p["value"].get("vtype")
    return None


def v192(obj):
    """Every RECURRENCE-ID's value type equals its component's DTSTART
    value type (designation: RECURRENCE-ID)."""
    ok = True
    for sub in obj["components"]:
        rid = [p for p in sub["props"] if p["name"] == "RECURRENCE-ID"]
        if rid:
            ok = ok and all(p["value"].get("vtype") == _vtype(sub, "DTSTART")
                            for p in rid)
    return ok


def _form(comp, name):
    for p in comp["props"]:
        if p["name"] == name:
            return p["value"].get("form")
    return None


def v193(obj):
    """RECURRENCE-ID is a date with local time IFF the component's
    DTSTART is (designation: RECURRENCE-ID)."""
    ok = True
    for sub in obj["components"]:
        for p in sub["props"]:
            if p["name"] == "RECURRENCE-ID":
                ok = ok and ((p["value"].get("form") == "local") ==
                             (_form(sub, "DTSTART") == "local"))
    return ok


def v194(obj):
    """When DTSTART is DATE-valued, RECURRENCE-ID's value is a calendar
    date the recurrence pattern generates (integer-day model)."""
    ok = True
    for sub in obj["components"]:
        if _vtype(sub, "DTSTART") != "DATE":
            continue
        d0 = next((p["value"]["day"] for p in sub["props"]
                   if p["name"] == "DTSTART"), None)
        rr = next((p["value"] for p in sub["props"]
                   if p["name"] == "RRULE"), None)
        for p in sub["props"]:
            if p["name"] != "RECURRENCE-ID":
                continue
            if p["value"].get("vtype") != "DATE" or rr is None:
                return False
            inst = [d0 + k * rr.get("step", 1)
                    for k in range(rr.get("COUNT", 1))]
            ok = ok and p["value"]["day"] in inst
    return ok


def v116(obj):
    """In a VTIMEZONE observance whose RRULE carries UNTIL, the UNTIL
    value equals the last onset the pattern generates from the
    observance's DTSTART (integer-day model)."""
    ok = True
    for sub in obj["components"]:
        if sub["type"] != "VTIMEZONE":
            continue
        for ob in sub["components"]:
            d0 = next((p["value"]["day"] for p in ob["props"]
                       if p["name"] == "DTSTART"), None)
            for p in ob["props"]:
                if p["name"] == "RRULE" and "UNTIL" in p["value"]:
                    inst = _instances_until(d0, p["value"]["step"],
                                            p["value"]["UNTIL"])
                    ok = ok and inst[-1] == p["value"]["UNTIL"]
    return ok


def v185(obj):
    """Where a delegate ATTENDEE (DELEGATED-FROM) and its delegator are
    co-listed in one component, the delegate's RSVP and ROLE equal the
    delegator's."""
    ok = True
    for sub in obj["components"]:
        att = {p["value"]: p for p in sub["props"]
               if p["name"] == "ATTENDEE"}
        for p in att.values():
            src = p["params"].get("DELEGATED-FROM")
            if src and src in att:
                q = att[src]
                ok = ok and (
                    p["params"].get("RSVP") == q["params"].get("RSVP")
                    and p["params"].get("ROLE") == q["params"].get("ROLE"))
    return ok


# --- fixtures for validators ----------------------------------------------

TZC = ("VCALENDAR", "VTIMEZONE", "DAYLIGHT")
EVC = ("VCALENDAR", "VEVENT")

REC_OK = C("VEVENT", [
    P("DTSTART", {"vtype": "DATE", "day": 10}, component=EVC),
    P("RRULE", {"FREQ": "DAILY", "step": 1, "COUNT": 5}, component=EVC),
    P("RECURRENCE-ID", {"vtype": "DATE", "day": 12}, component=EVC)])
REC_BADTYPE = C("VEVENT", [
    P("DTSTART", {"vtype": "DATE", "day": 10}, component=EVC),
    P("RRULE", {"FREQ": "DAILY", "step": 1, "COUNT": 5}, component=EVC),
    P("RECURRENCE-ID", {"vtype": "DATE-TIME", "day": 12,
                        "form": "local"}, component=EVC)])
REC_BADDAY = C("VEVENT", [
    P("DTSTART", {"vtype": "DATE", "day": 10}, component=EVC),
    P("RRULE", {"FREQ": "DAILY", "step": 1, "COUNT": 5}, component=EVC),
    P("RECURRENCE-ID", {"vtype": "DATE", "day": 30}, component=EVC)])
REC_LOCAL = C("VEVENT", [
    P("DTSTART", {"vtype": "DATE-TIME", "form": "local", "day": 10},
      component=EVC),
    P("RECURRENCE-ID", {"vtype": "DATE-TIME", "form": "local", "day": 10},
      component=EVC)])
REC_MIXED = C("VEVENT", [
    P("DTSTART", {"vtype": "DATE-TIME", "form": "local", "day": 10},
      component=EVC),
    P("RECURRENCE-ID", {"vtype": "DATE-TIME", "form": "utc", "day": 10},
      component=EVC)])


def tz_until(until):
    return OBJ([P("VERSION", "2.0")], [
        C("VTIMEZONE", [P("TZID", "Z")], [
            C("DAYLIGHT", [
                P("DTSTART", {"vtype": "DATE-TIME", "form": "local",
                              "day": 0}, component=TZC),
                P("RRULE", {"FREQ": "YEARLY", "step": 7, "UNTIL": until},
                  component=TZC)])])])


def deleg(rsvp_from, rsvp_to):
    return OBJ([P("VERSION", "2.0")], [
        C("VEVENT", [
            P("UID", "d@x", component=EVC),
            P("ATTENDEE", "mailto:a@x",
              params={"RSVP": rsvp_from, "ROLE": "REQ-PARTICIPANT",
                      "DELEGATED-TO": "mailto:b@x"}, component=EVC),
            P("ATTENDEE", "mailto:b@x",
              params={"RSVP": rsvp_to, "ROLE": "REQ-PARTICIPANT",
                      "DELEGATED-FROM": "mailto:a@x"}, component=EVC),
        ])])


DELEG_LONE = OBJ([P("VERSION", "2.0")], [
    C("VEVENT", [
        P("UID", "d2@x", component=EVC),
        P("ATTENDEE", "mailto:b@x",
          params={"RSVP": "TRUE", "ROLE": "REQ-PARTICIPANT",
                  "DELEGATED-FROM": "mailto:a@x"}, component=EVC)])])


WITNESSES = [
    # ---- IC1: stable DOMAIN ----
    VAL(63, "Within one RECUR value, a BYDAY rule part carries a numeric "
            "modifier only when the FREQ rule part is MONTHLY or YEARLY.",
        "prop", v63,
        accept=[P("RRULE", {"FREQ": "MONTHLY", "BYDAY": [(1, "MO")]},
                  component=EVC),
                P("RRULE", {"FREQ": "WEEKLY", "BYDAY": [(None, "MO")]},
                  component=EVC)],
        reject=[P("RRULE", {"FREQ": "WEEKLY", "BYDAY": [(2, "MO")]},
                  component=EVC)],
        quote=Q[63]),
    VAL(84, "A UTC-OFFSET value denoting an offset behind UTC carries the "
            "HYPHEN-MINUS sign character (convention 2: the abstract "
            "value carries encoding and denotation).",
        "prop", v84,
        accept=[P("TZOFFSETFROM", {"encoded_sign": "-",
                                   "offset_minutes": -300}, component=TZC)],
        reject=[P("TZOFFSETFROM", {"encoded_sign": "+",
                                   "offset_minutes": -300}, component=TZC)],
        quote=Q[84]),
    VAL(143, "The iCalendar object contains exactly one VERSION property "
             "at calendar level (registered designation: VERSION; the "
             "check's shape — count of the designated property equals "
             "one — is the same for any calendar-level property).",
        "object", v143,
        accept=[OBJ([P("VERSION", "2.0"), P("PRODID", "-//x//EN")])],
        reject=[OBJ([P("VERSION", "2.0"), P("VERSION", "2.0")]),
                OBJ([P("PRODID", "-//x//EN")])],
        quote=Q[143],
        pair_fine=PPAIR(
            P("VERSION", "2.0"),
            ctx("The rest of the object carries no other VERSION "
                "property: specified once — compliant.",
                "other-props", True, Q[143]),
            ctx("The rest of the object carries a second VERSION "
                "property: specified twice — violation. The lone "
                "content line is identical in both contexts.",
                "other-props", False, Q[143]))),

    # ---- IC3: the 192-194 cluster, single-rung {object} ----
    VAL(192, "Every RECURRENCE-ID property has the same value type as the "
             "DTSTART property of its recurring component (registered "
             "designation: RECURRENCE-ID).",
        "object", v192,
        accept=[OBJ([P("VERSION", "2.0")], [REC_OK])],
        reject=[OBJ([P("VERSION", "2.0")], [REC_BADTYPE])],
        quote=Q[192],
        pair_fine=PPAIR(
            P("RECURRENCE-ID", {"vtype": "DATE", "day": 12}, component=EVC),
            ctx("The component's DTSTART elsewhere in the object is "
                "DATE-valued: types match — compliant.",
                "other-props", True, Q[192]),
            ctx("The component's DTSTART elsewhere in the object is "
                "DATE-TIME-valued: types differ — violation. The "
                "RECURRENCE-ID line itself is identical.",
                "other-props", False, Q[192]))),
    VAL(193, "A RECURRENCE-ID is specified as a date with local time if "
             "and only if its component's DTSTART is (registered "
             "designation: RECURRENCE-ID).",
        "object", v193,
        accept=[OBJ([P("VERSION", "2.0")], [REC_LOCAL])],
        reject=[OBJ([P("VERSION", "2.0")], [REC_MIXED])],
        quote=Q[193],
        pair_fine=PPAIR(
            P("RECURRENCE-ID", {"vtype": "DATE-TIME", "form": "local",
                                "day": 10}, component=EVC),
            ctx("DTSTART elsewhere in the object is local-form: the "
                "biconditional holds — compliant.",
                "other-props", True, Q[193]),
            ctx("DTSTART elsewhere in the object is UTC-form: the "
                "biconditional fails — violation.",
                "other-props", False, Q[193]))),
    VAL(194, "When the component's DTSTART is DATE-valued, the "
             "RECURRENCE-ID value is a calendar date generated by the "
             "component's recurrence pattern (integer-day model; "
             "registered designation: RECURRENCE-ID).",
        "object", v194,
        accept=[OBJ([P("VERSION", "2.0")], [REC_OK])],
        reject=[OBJ([P("VERSION", "2.0")], [REC_BADDAY])],
        quote=Q[194],
        pair_fine=PPAIR(
            P("RECURRENCE-ID", {"vtype": "DATE", "day": 12}, component=EVC),
            ctx("DTSTART day 10 with a DAILY COUNT=5 pattern elsewhere "
                "in the object: day 12 is a generated instance — "
                "compliant.", "other-props", True, Q[194]),
            ctx("DTSTART day 40 with the same pattern: day 12 is not a "
                "generated instance — violation.",
                "other-props", False, Q[194]))),

    # ---- IC4: multi-rung 116 and 185 ----
    VAL(116, "Where an observance RRULE carries UNTIL, the UNTIL value "
             "equals the last onset the pattern generates from the "
             "observance's DTSTART (the sentence's own parenthetical, "
             "checkable in-object).",
        "object", v116,
        accept=[tz_until(21)],
        reject=[tz_until(20)],
        quote=Q[116],
        pair_fine=PPAIR(
            P("RRULE", {"FREQ": "YEARLY", "step": 7, "UNTIL": 21},
              component=TZC),
            ctx("The observance's DTSTART elsewhere in the object is day "
                "0: 21 is the last generated onset — compliant.",
                "other-props", True, Q[116]),
            ctx("The observance's DTSTART elsewhere in the object is day "
                "1: 21 is not a generated onset — violation.",
                "other-props", False, Q[116]))),
    PAIR(116, "An observance RRULE with no UNTIL is compliant only if the "
              "observance is not known to have an effective end date — "
              "the guard is knowledge of time-zone law, outside any "
              "object.",
         TZ_OBJ,
         ctx("The jurisdiction's daylight rule stands, no end date is "
             "known: an unbounded RRULE is correct — compliant.",
             "world-fact", True, Q[116]),
         ctx("The jurisdiction abolished the observance effective a "
             "known date: the same unbounded RRULE omits the required "
             "UNTIL — violation. The object is identical.",
             "world-fact", False, Q[116])),
    VAL(185, "Where a delegate ATTENDEE and its DELEGATED-FROM delegator "
             "are co-listed in one component, the delegate's RSVP and "
             "ROLE parameter values equal the delegator's.",
        "object", v185,
        accept=[deleg("TRUE", "TRUE")],
        reject=[deleg("FALSE", "TRUE")],
        quote=Q[185],
        pair_fine=PPAIR(
            P("ATTENDEE", "mailto:b@x",
              params={"RSVP": "TRUE", "ROLE": "REQ-PARTICIPANT",
                      "DELEGATED-FROM": "mailto:a@x"}, component=EVC),
            ctx("The delegator's ATTENDEE line elsewhere in the object "
                "carries RSVP=TRUE, ROLE=REQ-PARTICIPANT: inherited — "
                "compliant.", "other-props", True, Q[185]),
            ctx("The delegator's ATTENDEE line elsewhere carries "
                "RSVP=FALSE: not inherited — violation. The delegate's "
                "line is identical.", "other-props", False, Q[185]))),
    PAIR(185, "Where the delegator is NOT co-listed, inheritance binds "
              "against the delegating REQUEST — a different scheduling "
              "artifact.",
         DELEG_LONE,
         ctx("The delegating iTIP REQUEST carried RSVP=TRUE for the "
             "delegator: the delegate's RSVP=TRUE inherits it — "
             "compliant.", "other-artifacts", True, Q[185]),
         ctx("The delegating REQUEST carried RSVP=FALSE: the same "
             "object's RSVP=TRUE fails to inherit — violation.",
             "other-artifacts", False, Q[185])),

    # ---- IC2: stable PROCESS ----
    PAIR(69, "Invalid recurrence instances are excluded from the computed "
             "recurrence set — a property of the consumer's computation, "
             "not of the object.",
         INVALID_INSTANCE_OBJ,
         ctx("The consuming application drops the nonexistent-date "
             "instance from its computed recurrence set — compliant.",
             "party-conduct", True, Q[69]),
         ctx("The consuming application counts the nonexistent-date "
             "instance (e.g., rolls it forward) — violation. The object "
             "is identical.", "party-conduct", False, Q[69])),
    PAIR(118, "Onset instances are generated using DTSTART and "
              "TZOFFSETFROM — a constraint on the generating "
              "computation.",
         TZ_OBJ,
         ctx("The implementation computes onsets from DTSTART with "
             "TZOFFSETFROM — compliant.", "party-conduct", True, Q[118]),
         ctx("The implementation computes onsets using TZOFFSETTO, "
             "coincidentally emitting the same values for this zone — "
             "violation. The object is identical.",
             "party-conduct", False, Q[118])),
    PAIR(1, "Folded lines are unfolded FIRST when parsing — an ordering "
            "of the parser's internal steps.",
         FOLDED_OBJ,
         ctx("The parser unfolds the stream before content-line parsing "
             "— compliant.", "party-conduct", True, Q[1]),
         ctx("The parser tokenizes property names before unfolding and "
             "patches continuations afterward, arriving at the same "
             "abstract object — violation of 'MUST first'. The object "
             "is identical.", "party-conduct", False, Q[1])),

    # ---- IC2: stable U ----
    PAIR(200, "The UID value is globally unique — a relation to every "
              "other identifier in the world, not a property of one "
              "object.",
         UID_OBJ,
         ctx("No other calendar system ever issued 'u-7f3a' — the "
             "identifier is globally unique — compliant.",
             "other-artifacts", True, Q[200]),
         ctx("Another product independently issued 'u-7f3a' for an "
             "unrelated event — global uniqueness fails — violation. "
             "The object is identical.", "other-artifacts", False,
             Q[200])),
    PAIR(201, "The generator GUARANTEES uniqueness — a property of the "
              "generation process, not of the value it happened to "
              "emit.",
         UID_OBJ,
         ctx("The generator derives identifiers from a "
             "collision-managed scheme (host + monotonic counter): the "
             "guarantee exists — compliant.",
             "generation-process", True, Q[201]),
         ctx("The generator sampled a short random token with no "
             "collision management and got lucky: same value, no "
             "guarantee — violation.", "generation-process", False,
             Q[201])),
    PAIR(7, "Two values of one multi-valued property must not be "
            "language variants of one intended value — the guard is "
            "what the generator meant.",
         CAT_OBJ,
         ctx("The generator meant two distinct categories (a meeting "
             "about reunions) — compliant.",
             "private-intent", True, Q[7]),
         ctx("The generator meant one category expressed in English and "
             "French — violation. The property is identical.",
             "private-intent", False, Q[7])),

    # ---- IC3: contested conduct/intent/world items -> {nonlocal} ----
    PAIR(13, "Unrecognized x-param/iana-param values are ignored by the "
             "receiving application — receiver conduct over its own "
             "vocabulary.",
         XPARAM_OBJ,
         ctx("The receiver, not recognizing X-PRIORITY-HINT, processes "
             "the property as if the parameter were absent — compliant.",
             "party-conduct", True, Q[13]),
         ctx("The receiver, not recognizing X-PRIORITY-HINT, rejects "
             "the property — violation. The object is identical.",
             "party-conduct", False, Q[13])),
    PAIR(91, "Unrecognized x-comp/iana-comp values are ignored — "
             "receiver conduct.",
         XCOMP_OBJ,
         ctx("The receiver skips the X-DAILY-DIGEST component and "
             "processes the rest — compliant.",
             "party-conduct", True, Q[91]),
         ctx("The receiver aborts the import on the unrecognized "
             "component — violation.", "party-conduct", False, Q[91])),
    PAIR(146, "Unrecognized CLASS values are treated as PRIVATE — "
              "receiver conduct.",
         XCLASS_OBJ,
         ctx("The receiver applies its PRIVATE handling to the "
             "X-EYES-ONLY event — compliant.",
             "party-conduct", True, Q[146]),
         ctx("The receiver applies PUBLIC handling to the same event — "
             "violation.", "party-conduct", False, Q[146])),
    PAIR(150, "Values at the spec's stated precision are accepted — "
              "receiver conduct.",
         GEO_OBJ,
         ctx("The receiver accepts the six-decimal GEO value — "
             "compliant.", "party-conduct", True, Q[150]),
         ctx("The receiver rejects the six-decimal GEO value as too "
             "precise — violation.", "party-conduct", False, Q[150])),
    PAIR(210, "Alarms with unrecognized action values are ignored — "
              "receiver conduct.",
         XALARM_OBJ,
         ctx("The receiver ignores the X-FLASH-LIGHTS alarm and keeps "
             "the event — compliant.", "party-conduct", True, Q[210]),
         ctx("The receiver raises an error on the alarm — violation.",
             "party-conduct", False, Q[210])),
    PAIR(43, "A fixed time must be conveyed as UTC or TZID-referenced "
             "local time — the duty binds only when a FIXED time is "
             "what the generator is communicating.",
         FLOATING_OBJ,
         ctx("The generator meant a floating time (same wall-clock "
             "wherever the user is): the third, floating form is the "
             "correct choice — compliant.",
             "private-intent", True, Q[43]),
         ctx("The generator meant a fixed absolute instant: the same "
             "floating value fails to specify UTC or a time zone "
             "reference — violation.", "private-intent", False, Q[43])),
    PAIR(79, "A fixed time must be conveyed as UTC or TZID-referenced "
             "local time — the duty binds only when a FIXED time is "
             "what the generator is communicating. (Byte-identical "
             "sentence to item 43; the witness is deliberately the "
             "same, per IC5.)",
         FLOATING_OBJ,
         ctx("The generator meant a floating time (same wall-clock "
             "wherever the user is): the third, floating form is the "
             "correct choice — compliant.",
             "private-intent", True, Q[79]),
         ctx("The generator meant a fixed absolute instant: the same "
             "floating value fails to specify UTC or a time zone "
             "reference — violation.", "private-intent", False, Q[79])),
    PAIR(62, "Rule parts violating item 61's requirement are IGNORED "
             "when the consumer computes the recurrence — consumer "
             "conduct on an in-object trigger.",
         RECUR_VIOL_OBJ,
         ctx("The consumer computes the recurrence set as if BYHOUR "
             "were absent — compliant.", "party-conduct", True, Q[62]),
         ctx("The consumer applies the BYHOUR part when expanding — "
             "violation. The object is identical.",
             "party-conduct", False, Q[62])),
    PAIR(77, "A seconds value of 60 is used only where a positive leap "
             "second actually occurred — a fact of UTC history, not of "
             "the value.",
         LEAP_OBJ,
         ctx("At the denoted UTC instant a positive leap second was in "
             "effect: 60 accounts for it — compliant.",
             "world-fact", True, Q[77]),
         ctx("No leap second occurred at that instant: the same value "
             "60 is not accounting for one — violation.",
             "world-fact", False, Q[77])),
]

# --- recorded construction failures (honest outcomes, per README) ---------

FAILS = [
    {"item": 13, "rung": "prop", "reading":
        "A prop-local predicate deciding whether an application ignored "
        "an unrecognized x-param.",
     "reason": "The duty constrains receiver behavior, and the trigger "
               "('values they don't recognize') is the receiver's own "
               "vocabulary; the content line fixes neither.",
     "channel": "party-conduct"},
    {"item": 91, "rung": "prop", "reading":
        "A prop-local predicate deciding whether an application ignored "
        "an unrecognized x-comp.",
     "reason": "Same shape as 13: conduct duty on a recognition-set "
               "guard; the BEGIN line fixes neither.",
     "channel": "party-conduct"},
    {"item": 146, "rung": "prop", "reading":
        "A prop-local predicate deciding whether an unrecognized CLASS "
        "value was treated as PRIVATE.",
     "reason": "Treat-as-PRIVATE is receiver processing; no property "
               "content encodes it.",
     "channel": "party-conduct"},
    {"item": 150, "rung": "prop", "reading":
        "A prop-local predicate deciding whether a receiver accepted a "
        "value of the stated precision.",
     "reason": "Acceptance is receiver conduct; the GEO line is "
               "consistent with both acceptance and rejection.",
     "channel": "party-conduct"},
    {"item": 210, "rung": "prop", "reading":
        "A prop-local predicate deciding whether an alarm with an "
        "unrecognized action value was ignored.",
     "reason": "Ignoring an alarm is receiver conduct on the receiver's "
               "recognition set.",
     "channel": "party-conduct"},
    {"item": 43, "rung": "prop", "reading":
        "A prop-local predicate for 'fixed times are UTC or "
        "TZID-referenced' (e.g., rejecting all floating DATE-TIMEs).",
     "reason": "Floating time is a spec-legal third form when no fixed "
               "time is intended; the binding guard ('to properly "
               "communicate a fixed time') is generator intent, so any "
               "prop predicate either rejects legal floating values or "
               "accepts intent violations.",
     "channel": "private-intent"},
    {"item": 79, "rung": "prop", "reading":
        "Identical to item 43's failed prop reading (byte-identical "
        "sentence).",
     "reason": "Same as 43: the guard is generator intent.",
     "channel": "private-intent"},
    {"item": 62, "rung": "prop", "reading":
        "A prop-local predicate deciding compliance with 'these rule "
        "parts MUST be ignored'.",
     "reason": "Two independent blocks: the trigger (a RECUR value "
               "violating item 61's requirement) itself references the "
               "component's DTSTART value type — another content line — "
               "and the duty ('ignored') is consumer computation.",
     "channel": "party-conduct"},
    {"item": 77, "rung": "prop", "reading":
        "A prop-local predicate for 'seconds=60 only for positive leap "
        "seconds' (e.g., checking the instant against the leap-second "
        "table).",
     "reason": "The leap-second table is world history, published by "
               "IERS and time-varying — not a constant fixed by the "
               "spec text, which the registered local-predicate "
               "definition requires.",
     "channel": "world-fact"},
]
